namespace JWA_Randomizer.Enums
{
    public enum DinosaurName
    {
        Invalid = 0,

        Allosaurus,
        Amargasaurus,
        Apatosaurus,
        BaronyxGen2,
        Carnataurus,
        Deinocheirus,
        DimetrodonGen2,
        Dimorphodon,
        DracorexGen2,
        Einiasuchus,
        Einosaurus,
        ErlikosaurusGen2,
        Euoplocephalus,
        Gallimimus,
        Giraffatitan,
        Iguanodon,
        IrritatorGen2,
        Kaprosuchus,
        Majungasaurus,
        Miragaia,
        MonolophosaurusGen2,
        Nodosaurus,
        Nundasuchus,
        Ornithomimus,
        Parasaurolophus,
        Proceratosaurus,
        Sarcosuchus,
        Stegosaurus,
        Suchomimus,
        Suchotator,
        Tanycolagreus,
        Tarbosaurus,
        Tenontosaurus,
        TriceratopsGen2,
        TyrannosaurusRexGen2,
        Utahraptor,
        Velociraptor
    }
}